apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sankey-scorecard-postgres
  labels:
    app: sankey-scorecard
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
